# Generated by Django 5.1.1 on 2024-09-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update_date',
            field=models.DateField(),
        ),
    ]
