# Generated by Django 5.1.1 on 2024-09-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='This is the title of a blog', max_length=300)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('abstract', models.TextField(help_text='the abstract of this blog')),
                ('content', models.TextField(help_text='the content of the blog')),
            ],
        ),
    ]
